### ISSUE TITLE
[Feature request] Inhibit suspend while playing

### ISSUE THREAD

**Issue by Alexmitter** [vixalien/muzika#106]
It is a very useful feature especially for those of us using the app on a mobile device but I see it as useful for desktop users too.
Lollypop does the same, https://gitlab.gnome.org/World/lollypop/-/blob/master/lollypop/inhibitor.py

Currently we have to enter Settings -> Power and disable the sleep mechanism before starting to listen on the go and than go back and manually activate it again.

**Comment by vixalien** [comment]
Hmm. I would only consider inhibiting suspend when playing videos or looking at the lyrics, as you don't want your screen off in those cases. Are there any other use cases?

**Comment by Alexmitter** [comment]
On a phone you usually have the device playing music while being in your pocket, as the screen is off it will enter the sleep state as currently nothing is telling it to please don't. 
Inhibiting suspend and inhibiting the screen turning off are two different things. Suspend in the case of a mobile linux phone means Suspend to RAM.
