### ISSUE TITLE
[Feature request] Allow to set a default playback mode

### ISSUE THREAD

**Issue by Alexmitter** [vixalien/muzika#107]
This is something I wish the official app had too. I never want to watch the video version, but videos default to it so I always have to manually switch to the music mode. It would be great if we could define that Music mode is the default for videos too.

**Comment by vixalien** [comment]
So basically, you want that if you click on a "video", Muzika will play the "audio" instead?

**Comment by vixalien** [comment]
I'd suggest replacing your videos in your playlists by their audio tracks.

Clicking on a music video and hearing the album version playing is not
expected.

Also, note that if you change the Video tab to Music, all the other tracks
in your playlist will be updated to play their album versions.
