### ISSUE TITLE
[Feature request] Add Window Title

### ISSUE THREAD

**Issue by LinuxSBC** [vixalien/muzika#111]
Currently, the window title (shown in the Overview, for example) is com.vixalien.muzika. This does not look as good as if it were to use something like the [Gtk set_title function](https://docs.gtk.org/gtk4/method.Window.set_title.html) to set it to "Muzika" (or maybe something more complicated like what song is playing).

**Comment by vixalien** [comment]
Hi. Thanks.

Would it make more sense to make the title the current page (like Home,
Liked Songs, etc...)

**Comment by LinuxSBC** [comment]
Yes, that makes sense to me.
