### ISSUE TITLE
MPRIS D-Bus support

### ISSUE THREAD

**Issue by 890m319as** [vixalien/muzika#120]
Expected behavior:
`playerctl next` skips to the next song

Current behavior:
nothing happens, but `dbus-send --print-reply --dest=org.mpris.MediaPlayer2.Muzika /org/mpris/MediaPlayer2 org.mpris.MediaPlayer2.Player.Next works.`

https://wiki.archlinux.org/title/MPRIS

**Comment by 890m319as** [comment]
Might be an issue with playerctl, not sure

**Comment by vixalien** [comment]
Sounds like MPRIS works, but playerctl does not.

It might be an issue with that 3rd party software.

**Comment by 890m319as** [comment]
I tried reading the code for playerctl, but it was unreadable to me. I couldn't figure out what it was doing to get a list of all known players, so I assume it's just an issue with the software. It appears other people have had the same issue, but with Spotify, and just used raw dbus, and it worked.
https://gitlab.com/axdsop/nix-dotfiles/tree/master/Configs/polybar/scripts/mpris_player
