### ISSUE TITLE
Internet access by VPN only

### ISSUE THREAD

**Issue by Johndjk** [vixalien/muzika#123]
Many users like me are looking for alternative apps like this for privacy reasons.

For those who want to keep their data secure and private, avoiding identity leaks such as IP addresses, and still access data directly from Youtube's servers (to avoid Piped's slowness and instability), this would be an incredible feature.

**Comment by Johndjk** [comment]
Yes, this configuration is usually done in the VPN itself, but being available in the app prevents IP leaks if something goes wrong with the configuration. This would be an important privacy feature.

I'm not a technical person but I'll give you the link to an app that has implemented it and it's great for that: https://github.com/qbittorrent/qBittorrent.

**Comment by vixalien** [comment]
I mean... BitTorrent is a torrent app, and it's recommended to use those with VPNs on.

I don't really see why this would be required for a music streaming app in particular...

**Comment by Johndjk** [comment]
I thought that the privacy issue would be enough, especially an app specifically for Linux, which is an OS used by those who don't want to have their lives profiled by Bigtechs, but there is also the issue of censorship in several countries where many users will not be able to use the app.

That's why, if it's not possible to implement the VPN traffic option, many music streaming apps at least offer the option of an integrated proxy.

And I think that's totally important.

**Comment by vixalien** [comment]
To achieve the level of security you desire, developers would need to add a
toggle to each app. I don't like the approach given you can just add a
global proxy in your settings or turn on "Always On VPN". Every decent VPN
provide has this option.

And also, the reason why messaging and other apps support proxies is not
primarily for privacy, but do they can be used in countries like Iran or
Afghanistan where specific services are blocked.

**Comment by Johndjk** [comment]
I understand your position.

Thank you for developing this beautiful app!
