### ISSUE TITLE
Flatpak repository missing x86_64 build

### ISSUE THREAD

**Issue by gregthwuen** [vixalien/muzika#128]
When I installed Muzika from the latest x86_64 CI build, the remote `devel-origin` with the URL https://vixalien.github.io/muzika/repo was automatically added. But doing a `flatpak update`, I got the following error:

```
No such ref 'app/com.vixalien.muzika.Devel/x86_64/master' in remote devel-origin
```

I discovered that the x86_64 build indeed isn't part of the Flatpak repository deployed to GitHub pages. This seems to be a regression that happened between run 10 (commit 4682fc21ea1fc1847a6594592109bd001ca74b76) and 11 (commit 30ef140f040b9cce38eb4d5790f256160eb59497) of the `pages-build-deployment` action. I'm not very familiar with the way GitHub actions work, so unfortunately I can't tell you the cause of the problem.

PS: You seem to have leaked a revocation certificate for the remote's PGP key in e70229a240e58bf21cdd68db55aebc4104269d6c. You might want to create a new key before using this one long-term.

**Comment by vixalien** [comment]
That's true. I was trying to setup Flatter, but it's very confusing and to be honest depressing.

I am going to revert all changes and have a manual CI build like before.

**Comment by gregthwuen** [comment]
Thanks. Probably the best solution atm, so at least flatpak doesn't error out anymore.

Would it help if I tried to figure out the problem with Flatter when I have some time on my hands, or should I just wait for the v1 release on Flathub?

**Comment by vixalien** [comment]
It would help tremendously even if I'm not going to use the data.

Flatter is a bit of a young project, and your research may help in other projects.
