### ISSUE TITLE
flatpak confusion

### ISSUE THREAD

**Issue by tdeboeser** [vixalien/muzika#166]
Hi,
 I'm trying install muzika via the readme, but the command: (using *Devel* because thats the nightly dl file, and the command fails "no such file" otherwise)

`flatpak install com.vixalien.muzika.Devel.flatpak`

returns:

`error: The application com.vixalien.muzika.Devel/x86_64/master requires the runtime org.gnome.Platform/x86_64/master which was not found`

But:  

```
flatpak remote-add --if-not-exists --user gnome-nightly https://nightly.gnome.org/gnome-nightly.flatpakrepo
flatpak install --user org.gnome.Platform//master
Looking for matches…
Skipping: org.gnome.Platform/x86_64/master is already installed
```

I don't think I missed a step.  How can I correct this?  

Thanks

**Comment by vixalien** [comment]
Hi.

It seems like you are trying to install Musial in the system (default) installation instead of the user installation where the GNOME master runtime is installed.

Simply run the following command to install Muzika correctly:

```sh
flatpak install --user com.vixalien.muzika.Devel.flatpak
```

**Comment by tdeboeser** [comment]
Awesome! thanks that worked.   But on the "Read Me", GitHub code page the command is: 

flatpak install com.vixalien.muzika.flatpak

**Comment by vixalien** [comment]
Thanks, will fix that
