### ISSUE TITLE
Arch Linux package issue

### ISSUE THREAD

**Issue by nebulosa2007** [vixalien/muzika#171]
I'm trying to write PKGBUILD for `mizuka-git`, but I can't package the already compiled files into a package, the command in PKGBUILD - `meson install -C build --destdir "$pkgdir"` gets an error:
```console
ninja: Entering directory `/build/muzika-git/src/build'
[1/3] Generating src/yarn-deps with a custom command
FAILED: src/node_modules 
/usr/bin/yarn --cwd /build/muzika-git/src/muzika install
Error: EACCES: permission denied, open '/root/.config/yarn'
    at Object.openSync (node:fs:573:18)
    at readFileSync (node:fs:452:35)
    at /usr/lib/node_modules/yarn/lib/util/rc.js:89:58
    at Array.map (<anonymous>)
    at parseRcPaths (/usr/lib/node_modules/yarn/lib/util/rc.js:87:37)
    at Object.findRc (/usr/lib/node_modules/yarn/lib/util/rc.js:101:10)
    at getRcConfigForCwd (/usr/lib/node_modules/yarn/lib/rc.js:54:47)
    at Object.<anonymous> (/usr/lib/node_modules/yarn/lib/cli/index.js:569:58)
    at Generator.next (<anonymous>)
    at step (/usr/lib/node_modules/yarn/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
ninja: build stopped: subcommand failed.
Could not rebuild /build/muzika-git/src/build
```
How I can fix it?

**Comment by vixalien** [comment]
sorry, I don't use arch linux anymore. let me disown the package and you can probably be the new maintainer if you end up fixing the issue.

**Comment by nebulosa2007** [comment]
My point is not in Arch Linux but in command `meson install -C build --destdir "$pkgdir"` only. It doesn't matter what distributive are you using: Fedora, Arch or whatever.

The `yarn` somehow trying get `/root/.config/yarn` file, which does not exist.

I could be maintainer for your app in AUR (package not exists for now), but need a little help with issue.

I already tried to set `yarnrc`- It works, but got another error - `empty yarn file`

**Comment by vixalien** [comment]
Your original error means that you're trying to run `yarn` as root (which is why it's looking for the config in `/root`). Did you try running yarn as a non-root user?

**Comment by amotrak** [comment]
@vixalien thank you in advance for such a wonderful YouTube music client, even though it is still in alpha, it is so far the best yt music player I have seen, comparing to all that electron crap other people made. I have also [created](https://aur.archlinux.org/packages/muzika-git) an AUR package, for those who don't want or can't use flatpak, would be great to include that information in readme.

I don't have an experience with Adwaita, but would be grateful if you kindly tell me if you are planning to stay on libadwaita nightly or move to stable as soon as all the needed features would be merged?

**Comment by vixalien** [comment]
I'll probably keep depending on adwaita main as long as the app is NOT stable.

I also can't possibly link the AUR as it might cause users to think I support the environment, which I don't really. I would probably add a repology though when the app is stable.

Thanks for the kind words too, they're appreciated
