### ISSUE TITLE
crash on start with "JS ERROR: Error: Failed to create gtk4paintablesink"

### ISSUE THREAD

**Issue by violoncelloCH** [vixalien/muzika#172]
Hi,
Thanks for the promising looking app! I tried installing it on Fedora 40 following the instructions (as a Flatpak). However when starting the app, it doesn't launch. When starting from the terminal, I get the following error output:

```
$ flatpak run com.vixalien.muzika.Devel 
Gjs-Console-Message: 10:21:28.041: caching soup requests at /home/jonas/.var/app/com.vixalien.muzika.Devel/cache/com.vixalien.muzika.Devel/soup-cache

(com.vixalien.muzika.Devel:2): Gjs-CRITICAL **: 10:21:28.823: JS ERROR: Error: Failed to create gtk4paintablesink, is that installed on your system?
MuzikaMediaStream@resource:///com/vixalien/muzika/js/main.js:27267:13
MuzikaPlayer@resource:///com/vixalien/muzika/js/main.js:27574:5
Application@resource:///com/vixalien/muzika/js/main.js:30957:20
main@resource:///com/vixalien/muzika/js/main.js:31074:15
run@resource:///org/gnome/gjs/modules/script/package.js:207:19
@file:///app/bin/com.vixalien.muzika.Devel:22:40
@file:///app/bin/com.vixalien.muzika.Devel:28:6
```

Am I missing something?

**Comment by vixalien** [comment]
Im suddenly getting this error too. Will look into it soon

**Comment by rayzr522** [comment]
having this issue as well. perhaps related to this? https://discourse.gnome.org/t/creating-gstreamer-sink-for-widget-in-gtk4-application/13220/5

> gtk4paintablesink is not included in the Flatpak SDK yet, see [Ship gst-plugins-rs together with the other GStreamer components (#1502) · Issues · freedesktop-sdk / freedesktop-sdk · GitLab 35](https://gitlab.com/freedesktop-sdk/freedesktop-sdk/-/issues/1502).
> 
> You would have to build it as part of your Flatpak application.

i am not familiar with gtk4 development but the implication of those 2 urls seems to be that you yourself need to ensure the right gst plugins are included in the flatpak

**Comment by vixalien** [comment]
> you yourself need to ensure the right gst plugins are included in the flatpak

Yes indeed, we are building the `gst-plugins-rs` ourselves in the flatpak (see https://github.com/vixalien/muzika/blob/main/build-aux/flatpak/modules/gst-plugin-gtk4.json) however a recent update or something caused it not to be packaged correctly...
