### ISSUE TITLE
I cant install nightly flatpak. Remote Devel-Origin not found

### ISSUE THREAD

**Issue by Hedronmx** [vixalien/muzika#186]
When trying to run
flatpak install --user com.vixalien.muzika.flatpak
error: Remote "devel-origin" not found

I have no clue how to add devel origin remote

**Comment by vixalien** [comment]
Hmm. Not sure what's the issue. Try to remove any leftover data you might have:

```
flatpak uninstall com.vixalien.muzika
flatpak uninstall com.vixalien.muzika.Devel
flatpak --user remote-delete devel-origin
```

Then download and install the [latest Nightly Flatpak](https://github.com/vixalien/muzika/blob/main/vixalien.github.io/muzika/muzika.flatpakref). This will auto-update.
