### ISSUE TITLE
Previous song action annoying behavior

### ISSUE THREAD

**Issue by AdrianVovk** [vixalien/muzika#193]
In pretty much every music app I've used, the behavior of the "previous song" action is like follows:
- If you're within the first 5 seconds of a song, it'll go to the previous song
- If you're further into a song than the first 5 seconds, it just restarts the song from the beginning

Muzika doesn't have this behavior, so often I want to restart a song and it ends up buffering the previous song. So if I want to restart a song, I have to go to the previous song, wait, then go back to the next song, and wait again.

My workaround also doesn't work if I happen to be listening to the very first song in a playlist; the "previous song" action is greyed out - other players leave the action always available. If there's no previous song, it just always restarts the current song.

**Comment by vixalien** [comment]
Please test if #196 fixed this and reopen if otherwise!

**Comment by vixalien** [comment]
Oops seems like it's not merged yet

**Comment by vixalien** [comment]
merged!
