### ISSUE TITLE
No way to play video on desktop

### ISSUE THREAD

**Issue by AdrianVovk** [vixalien/muzika#194]
With the recent rework of the desktop's "Now playing" UI (in #180), there's no way to play a music video for a song.

My workaround is to shrink the size of the app into a mobile size, then open the now-playing view, then switch it to video, then grow the app again.

**Comment by DaPigGuy** [comment]
Duplicate of #187

**Comment by AdrianVovk** [comment]
Whoops no idea how I didn't find that one... Sorry for the noise
