### ISSUE TITLE
support for add/remove track from playlist

### ISSUE THREAD

**Issue by onny** [vixalien/muzika#20]

**Comment by vixalien** [comment]
I'm working on this!

**Comment by vixalien** [comment]
you can now delete tracks from a playlist, but I'm not sure how reliable it is. you can help test it

**Comment by vixalien** [comment]
you can now also add playlists from the suggested songs.

adding any song to a playlist will be coming soon

**Comment by vixalien** [comment]
done!!!!

**Comment by onny** [comment]
wow impressive, going to check it out on my linux phone tomorrow!
