### ISSUE TITLE
Flatpak nightly not running?

### ISSUE THREAD

**Issue by igorgue** [vixalien/muzika#204]
Hi,

I'm using NixOS and I wanted to try the latest flatpak nightly but it doesn't run / do anything?

```bash
> flatpak run com.vixalien.muzika.Devel
Gjs-Console-Message: 10:47:01.107: caching soup requests at /home/igor/.var/app/com.vixalien.muzika.Devel/cache/com.vixalien.muzika.Devel/soup-cache
~ 
>  echo $?                  
139
```

I'm also running Hyprland, but will try on Gnome right now

**Comment by igorgue** [comment]
On Gnome:

```
> flatpak run com.vixalien.muzika.Devel
Gjs-Console-Message: 10:53:02.090: caching soup requests at /home/igor/.var/app/com.vixalien.muzika.Devel/cache/com.vixalien.muzika.Devel/soup-cache
Gdk-Message: 10:53:02.412: Error 71 (Protocol error) dispatching to Wayland display.
```

**Comment by vixalien** [comment]
Hmm did you make sure to run a `flatpak update com.vixalien.muzika.Devel`?

**Comment by vixalien** [comment]
Also, please output the result of running `flatpak info com.vixalien.muzika.Devel`

**Comment by igorgue** [comment]
```bash
  flatpak info com.vixalien.muzika.Devel  

Muzika - Elegant music streaming application

          ID: com.vixalien.muzika.Devel
         Ref: app/com.vixalien.muzika.Devel/x86_64/master
        Arch: x86_64
      Branch: master
     Version: nightly
     License: GPL-3.0
      Origin: devel-origin
  Collection: 
Installation: system
   Installed: 2.7 MB
     Runtime: org.gnome.Platform/x86_64/master
         Sdk: org.gnome.Sdk/x86_64/master

      Commit: a5e3c07f8be32ac056fee023a4c59a41a252ed9558cc0a4aec355e745cabe14a
      Parent: 4212bb628a6de4c24f9fd509e02c929440d7b0385542c4a09a7daf43051a6c01
     Subject: Export com.vixalien.muzika.Devel
        Date: 2024-09-19 17:17:22 +0000
```

I did update too even though this is my first install, same issue, here's the info command.

**Comment by igorgue** [comment]
@vixalien anything else I can do? Maybe to display more debug information.

**Comment by vixalien** [comment]
im pretty sure this is an issue specific to you as i've not hit it yet. the best we can do is probably wait for other users to encounter this

**Comment by vixalien** [comment]
Try to see `GSK_RENDERER=ngl` with Flatseal and see if the app launches that way

**Comment by igorgue** [comment]
@vixalien yes! thank you that did it! What does setting that do?

**Comment by vixalien** [comment]
The new GTK default renderer is now Vulkan, instead of GL and that may cause issues on some systems.

Please file an upstream GTK bug if it doesn't exist yet.
