### ISSUE TITLE
Cutted off buttons on album/artist list

### ISSUE THREAD

**Issue by diegopvlk** [vixalien/muzika#205]
The buttons are not aligned properly, can be fixed by setting margin end here:

https://github.com/vixalien/muzika/blob/bb85dad038dad3a9b2e8d3c756eafd77c4eb3f65/src/components/playlist/columnview/columns/menu.ts#L56-L57

`box.set_margin_end(14);`

Before
![Before](https://github.com/user-attachments/assets/46d263be-0725-4214-b40c-bb1dd994c5cd)

After
![After](https://github.com/user-attachments/assets/b39f5d2f-d336-4724-96dc-ec3734f2d9b4)

**Comment by vixalien** [comment]
Yes please. I would appreciate a PR
