### ISSUE TITLE
App crashing when trying to play a song

### ISSUE THREAD

**Issue by alvaroburns** [vixalien/muzika#208]
Everytime I try to play a song the app crashes. It is updated (this problem was not happening before the latest update). I'm using the nightly flatpak on Fedora Silverblue 41 Beta.

    Hardware Model: Lenovo IdeaPad Flex 5 14IIL05
    Processor: Intel® Core™ i5-1035G1 × 8

**Comment by vixalien** [comment]
Can you post the logs when you run the app in the terminal using

```sh
flatpak run com.vixalien.muzika.Devel
```

**Comment by alvaroburns** [comment]
> Can you post the logs when you run the app in the terminal using
> 
> ```shell
> flatpak run com.vixalien.muzika.Devel
> ```

This is what I've got running the command and trying to play a song:

$ flatpak run com.vixalien.muzika.Devel
Gjs-Console-Message: 20:36:35.826: caching soup requests at /var/home/burns/.var/app/com.vixalien.muzika.Devel/cache/com.vixalien.muzika.Devel/soup-cache
MESA-INTEL: warning: ../src/intel/vulkan/anv_formats.c:763: FINISHME: support YUV colorspace with DRM format modifiers
MESA-INTEL: warning: ../src/intel/vulkan/anv_formats.c:794: FINISHME: support more multi-planar formats with DRM modifiers

(com.vixalien.muzika.Devel:2): Gjs-Console-CRITICAL **: 20:36:36.774: Permission to run in the background not granted

(com.vixalien.muzika.Devel:2): Gtk-CRITICAL **: 20:36:38.181: gtk_filter_match: assertion 'item != NULL' failed

(com.vixalien.muzika.Devel:2): GLib-GObject-CRITICAL **: 20:36:38.181: g_object_unref: assertion 'G_IS_OBJECT (object)' failed

(com.vixalien.muzika.Devel:2): Gtk-CRITICAL **: 20:36:38.181: gtk_filter_match: assertion 'item != NULL' failed

(com.vixalien.muzika.Devel:2): GLib-GObject-CRITICAL **: 20:36:38.181: g_object_unref: assertion 'G_IS_OBJECT (object)' failed

(com.vixalien.muzika.Devel:2): Gtk-CRITICAL **: 20:36:38.185: gtk_filter_match: assertion 'item != NULL' failed

(com.vixalien.muzika.Devel:2): GLib-GObject-CRITICAL **: 20:36:38.185: g_object_unref: assertion 'G_IS_OBJECT (object)' failed

(com.vixalien.muzika.Devel:2): Gtk-CRITICAL **: 20:36:38.185: gtk_filter_match: assertion 'item != NULL' failed

(com.vixalien.muzika.Devel:2): GLib-GObject-CRITICAL **: 20:36:38.185: g_object_unref: assertion 'G_IS_OBJECT (object)' failed

(com.vixalien.muzika.Devel:2): Gtk-CRITICAL **: 20:36:38.188: gtk_filter_match: assertion 'item != NULL' failed

(com.vixalien.muzika.Devel:2): GLib-GObject-CRITICAL **: 20:36:38.188: g_object_unref: assertion 'G_IS_OBJECT (object)' failed

(com.vixalien.muzika.Devel:2): Gtk-CRITICAL **: 20:36:38.188: gtk_filter_match: assertion 'item != NULL' failed

(com.vixalien.muzika.Devel:2): GLib-GObject-CRITICAL **: 20:36:38.188: g_object_unref: assertion 'G_IS_OBJECT (object)' failed

(com.vixalien.muzika.Devel:2): Gtk-CRITICAL **: 20:36:38.191: gtk_filter_match: assertion 'item != NULL' failed

(com.vixalien.muzika.Devel:2): GLib-GObject-CRITICAL **: 20:36:38.191: g_object_unref: assertion 'G_IS_OBJECT (object)' failed

(com.vixalien.muzika.Devel:2): Gtk-CRITICAL **: 20:36:38.191: gtk_filter_match: assertion 'item != NULL' failed

(com.vixalien.muzika.Devel:2): GLib-GObject-CRITICAL **: 20:36:38.191: g_object_unref: assertion 'G_IS_OBJECT (object)' failed

**Comment by vixalien** [comment]
Are you running Muzika on a GNOME system?

**Comment by alvaroburns** [comment]
> Are you running Muzika on a GNOME system?

Yes! I'm on Fedora Silverblue 41 Beta with GNOME 47.

**Comment by alvaroburns** [comment]
# System Details Report
---

## Report details
- **Date generated:**                              2024-09-25 20:49:01

## Hardware Information:
- **Hardware Model:**                              Lenovo IdeaPad Flex 5 14IIL05
- **Memory:**                                      8.0 GiB
- **Processor:**                                   Intel® Core™ i5-1035G1 × 8
- **Graphics:**                                    Intel® UHD Graphics (ICL GT1)
- **Disk Capacity:**                               256.1 GB

## Software Information:
- **Firmware Version:**                            ECCN36WW
- **OS Name:**                                     Fedora Linux 41.20240925.n.0 (Silverblue Prerelease)
- **OS Build:**                                    (null)
- **OS Type:**                                     64-bit
- **GNOME Version:**                               47
- **Windowing System:**                            Wayland
- **Kernel Version:**                              Linux 6.11.0-63.fc41.x86_64

**Comment by vixalien** [comment]
Interesting can you try running the flatpak run command again?

**Comment by alvaroburns** [comment]
> Interesting can you try running the flatpak run command again?

This:
flatpak run com.vixalien.muzika.Devel
Gjs-Console-Message: 21:04:54.368: caching soup requests at /var/home/burns/.var/app/com.vixalien.muzika.Devel/cache/com.vixalien.muzika.Devel/soup-cache
MESA-INTEL: warning: ../src/intel/vulkan/anv_formats.c:763: FINISHME: support YUV colorspace with DRM format modifiers
MESA-INTEL: warning: ../src/intel/vulkan/anv_formats.c:794: FINISHME: support more multi-planar formats with DRM modifiers

(com.vixalien.muzika.Devel:2): Gjs-Console-CRITICAL **: 21:04:54.849: Permission to run in the background not granted

**Comment by alvaroburns** [comment]
I removed the app and installed it back again. Now it's working fine! Don't really know what happened, but the problem is gone.

**Comment by vixalien** [comment]
That's good to know.
