### ISSUE TITLE
Not playing any song

### ISSUE THREAD

**Issue by BruceWayne-Linux** [vixalien/muzika#219]
The app does not play anything. with or without logged in.
with login it seems to give an error that says "can't fetch"
without login, when clicked on any song, it just seems to load for infinity. it does not play anything, just keeps loading.
when ran from terminal, it give the following:

' Gjs-Console-Message: 18:14:29.191: caching soup requests at /home/peter/.var/app/com.vixalien.muzika.Devel/cache/com.vixalien.muzika.Devel/soup-cache
MESA-INTEL: warning: Haswell Vulkan support is incomplete
MESA-INTEL: warning: ../src/intel/vulkan_hasvk/anv_formats.c:752: FINISHME: support YUV colorspace with DRM format modifiers
MESA-INTEL: warning: ../src/intel/vulkan_hasvk/anv_formats.c:783: FINISHME: support more multi-planar formats with DRM modifiers

(com.vixalien.muzika.Devel:2): Gjs-Console-CRITICAL **: 18:14:31.729: couldn't load current track TypeError: response.streamingData is undefined
get_song@resource:///com/vixalien/muzika/js/main.js:11407:5
async*load_new_track_metadata@resource:///com/vixalien/muzika/js/main.js:28123:7
load_new_track@resource:///com/vixalien/muzika/js/main.js:28152:16
current_track_changed_cb@resource:///com/vixalien/muzika/js/main.js:28165:15
change_position@resource:///com/vixalien/muzika/js/main.js:25462:10
load_settings_state@resource:///com/vixalien/muzika/js/main.js:28264:16
async*MuzikaPlayer@resource:///com/vixalien/muzika/js/main.js:28048:10
Application2@resource:///com/vixalien/muzika/js/main.js:32409:20
main@resource:///com/vixalien/muzika/js/main.js:32528:15
run@resource:///org/gnome/gjs/modules/script/package.js:207:19
@file:///app/bin/com.vixalien.muzika.Devel:22:40
@file:///app/bin/com.vixalien.muzika.Devel:28:6
'
(ignore the mesa warning, it never really affects working of anything)

**Comment by vixalien** [comment]
Yep, it's related to YouTube changing the auth mechanism, See #217

**Comment by BruceWayne-Linux** [comment]
Oh, so even without the login stuff also got affected?
well, hoping the community finds a fix soon.
