### ISSUE TITLE
provide flatpak for aarch64

### ISSUE THREAD

**Issue by onny** [vixalien/muzika#22]

**Comment by onny** [comment]
While trying to cross compile / build Muzika for aarch64 on NixOS I get following error

```
flatpak-builder --arch=aarch64 _flatpak build-aux/flatpak/com.vixalien.muzika.json
```

```
========================================================================
Building module libyaml in /home/onny/projects/muzika/.flatpak-builder/build/libyaml-4
========================================================================
Note: switching to 'f8f760f7387d2cc56a2fc7b1be313a3bf3f7f58c'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by switching back to a branch.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -c with the switch command. Example:

  git switch -c <new-branch-name>

Or undo this operation with:

  git switch -

Turn off this advice by setting config variable advice.detachedHead to false

HEAD is now at f8f760f ci: Fix build on macOS (#230)
bwrap: execvp ./bootstrap: No such file or directory
Error: module libyaml: module libyaml: Child process exited with code 1
```

Not sure if this problem is related to Muzika, or it's dependencies, my system configuration or Flatpak :(

**Comment by vixalien** [comment]
okay, so I just implemented the aarch64 build, but the non-nightly version is still building (30 minutes and counting) and it still haven't compiled GTK yet.

I have around 3000 minutes of CI minutes per month in my plan, and it doesn't take a lot of math to realize that it will only take around 100 runs for the minutes to be exhausted. This is why I think the best move forward is to only build aarch64 builds for Nightly flatpak.

Note that to use the nightly flatpak, you'll need to use `org.gnome.Sdk//master` from the `gnome-nightly` flatpak repo.

**Comment by vixalien** [comment]
haha I'm reallly really happy to see this lol. Do you mind if I use this on a mastodon post?

For the oversized buttons (which make the whole window overflow) I had some ideas do solve this, but the best one, which I just implemented is to put the "menu" button in the headerbar. take a look and let me know how it looks like.

since you have a phone, maybe you could tell me other areas that need optimising??

**Comment by onny** [comment]
Yes I’ll check other issues soon and open bug reports if thats okay for you :)

Feel free to use these pictures, our Mastodon handle is @pi_crew@chaos.social in case you want to tag us.

Thank you for these nice improvements 👍
