### ISSUE TITLE
Cant donate you on KoFI

### ISSUE THREAD

**Issue by Hedronmx** [vixalien/muzika#23]
I wont accept my payments for some reason. Do you have any other way of donating to you? I love this app

**Comment by vixalien** [comment]
Interesting. I don't know many payment platforms, so I chose ko-fi. Do you know other payment platform I could use?? github sponsors & stripe don't work in my country.

If you use paypal you can send me money at `geo + anger + cola [at] gmail [dot] com`

(don't mind the plus signs and spaces)

**Comment by Mars7x** [comment]
I've seen other devs using Liberapay, maybe you could try that?

**Comment by vixalien** [comment]
/

**Comment by vixalien** [comment]
sorry I closed this issue erroneously

**Comment by vixalien** [comment]
from your advice, I created a [liberapay account](https://liberapay.com/vixalien) and you can use that to donate to me

**Comment by Hedronmx** [comment]
I tried sending you a donation via PayPal, and it seems to be an issue with your account. The error says the recipient can't receive payments right now. So maybe check that out.

I'll try librepay

**Comment by vixalien** [comment]
yep. it's an issue with PayPal itself (not me). they seem to systematically refuse all transfers to accounts from my country (Rwanda)

it seems like all payment handlers used by these platforms don't really work with my country.

I tried creating a [buymeacoffee](https://bmc.link/vixalien) but I couldn't test by transferring myself some money. maybe you can see if it works??

**Comment by Hedronmx** [comment]
buy me a coffee worked! Sent you some coffees haha! Thanks man for your great app

**Comment by vixalien** [comment]
thank you!!!
