### ISSUE TITLE
Sometimes time tracking does not work

### ISSUE THREAD

**Issue by Hedronmx** [vixalien/muzika#24]
Sometimes the time tracking or scrobbler does not work. I will remain on 00:00 until you pause and play again.

**Comment by vixalien** [comment]
yep I can see this too. sometimes it freezes when you resize the app to and from the mobile view (collapsing the side bar).

I'm trying to implement a better player backend and I hope that to fix this issue.

**Comment by vixalien** [comment]
this should be fixed by #29
