### ISSUE TITLE
Weird artifacts on the artist cricle masked image

### ISSUE THREAD

**Issue by Hedronmx** [vixalien/muzika#25]
When scrolling through the home page, Artist's images start to flickering showing the mask (Square photo to circle photo)

**Comment by vixalien** [comment]
Yes I can see that too. I think it's an issue with libadwaita itself, although I don't have any idea. I'll create an issue upstream.

**Comment by vixalien** [comment]
I think it's a libadwaita issue, I created a [bug report](https://gitlab.gnome.org/GNOME/libadwaita/-/issues/699)

**Comment by vixalien** [comment]
Hello. Can you check if this is still the case? Because GTK switched to a new renderer (NGL) by default, I think this should be fixed for you.

**Comment by Hedronmx** [comment]
Seems fixed!

**Comment by vixalien** [comment]
Need to fix this on DynamicImage Avatars
