### ISSUE TITLE
Skipping through songs fast causes the wrong song to be played

### ISSUE THREAD

**Issue by Mars7x** [vixalien/muzika#26]
If you skip through music fast (or while the music is loading?) sometimes the wrong song will start playing.

**Comment by vixalien** [comment]
you should check to see if #29 fixed it!

**Comment by Mars7x** [comment]
I downloaded the artifact in that PR, but it seems to still happen. After 10 seconds of the wrong song being played it either plays the right song, or it plays another random song. 

Here is a video of it happening:

https://github.com/vixalien/muzika/assets/112448675/0f6d9623-58a2-4db3-8c97-306985a14501

**Comment by vixalien** [comment]
hmmm interesting. I remember putting in a lot of effort in the PR to make sure this doesn't happen anymore.

maybe you can try again with the most recent commits/artifacts and let me know what happens


https://github.com/vixalien/muzika/assets/37999241/2271f57b-8dbf-496e-8863-4c6dbc55099d

**Comment by Mars7x** [comment]
I tried the latest artifact and it still seems to be doing it. 
FWIW I downloaded the artifact from here: https://github.com/vixalien/muzika/actions/runs/5514279840
Maybe I downloaded the wrong one?

I am gonna try it in a virtual machine just to make sure that it isn't a Fedora problem.

**Comment by Mars7x** [comment]
I think I am downloading the wrong file because I tried it on a virtual machine and on another pc and it still happens.

**Comment by Mars7x** [comment]
I built the muzika-player branch from source and the issue is actually fixed there, so idk really know what the issue was.
Thanks for fixing this! :)
