### ISSUE TITLE
[mobile] Starting search doesn't change view

### ISSUE THREAD

**Issue by onny** [vixalien/muzika#31]
After entering search query, hitting "return" on the mobile keyboard doesn't have any effect. I guess the view changes in the background but on mobile it stays on the menu view.

![signal-2023-07-12-124852_002](https://github.com/vixalien/muzika/assets/757752/0c6e9371-7d00-4c20-9e70-5ce20337ed8d)

Best regards
Jonas

**Comment by vixalien** [comment]
looking into this
