### ISSUE TITLE
[mobile] playlist view: press on song doesnt start playback

### ISSUE THREAD

**Issue by onny** [vixalien/muzika#32]
I guess in some cases starting playback works for tapping on a track. Unfortunatley it doesn't work on the playlist view:

![signal-2023-07-12-124835_002](https://github.com/vixalien/muzika/assets/757752/215744c5-197b-4d89-9263-dc3229746fdf)

Trying to start playback by tapping on the track doesn't work

**Comment by vixalien** [comment]
AHH this is because of the double tap to play. I'll be instead looking for ways to make single tap to play
