### ISSUE TITLE
[mobile] search view layout issues

### ISSUE THREAD

**Issue by onny** [vixalien/muzika#33]
![signal-2023-07-12-124822_002](https://github.com/vixalien/muzika/assets/757752/8f4444e4-d81a-4748-982b-ac1f0c2ce6c6)

Best regards
Jonas

**Comment by vixalien** [comment]
hmm that looks normal to me. could you specify what's wrong?

**Comment by onny** [comment]
Ah you're right, I missed that it's possible to swipe through the upper menu and filter modal. Sorry for the confusion
