### ISSUE TITLE
Carousels block vertical scroll

### ISSUE THREAD

**Issue by DaPigGuy** [vixalien/muzika#45]
When the cursor hovers over a carousel, scrolling vertically is not possible until you move the cursor off, despite the carousel itself being scrollable only horizontally. This is especially noticeable on the home page.

Commit 997ae24d8d5988a2be10538d000cb69910d6f6d2

**Comment by vixalien** [comment]
I believe this is GTK's behavior, nothing we can do on this front except filing an issue.

I saw this earlier but couldn't do anything, However, the behavior works well on touchscreens.

**Comment by vixalien** [comment]
relevant: https://gitlab.gnome.org/GNOME/gtk/-/merge_requests/2953

**Comment by vixalien** [comment]
Closing as this is a GTK issue
