### ISSUE TITLE
time column missing on artist page

### ISSUE THREAD

**Issue by onny** [vixalien/muzika#46]
Testing the latest unstable 2023-07-27

![image](https://github.com/vixalien/muzika/assets/757752/b50c8825-eb7a-44ef-a9be-c79a8f585760)

Time column missing on tracks table on the right side

**Comment by vixalien** [comment]
that's an issue with the way YTM returns data: sometimes it gives duration, and sometimes it doesn't. I'll work on hiding the label tho if there is no time overall...
