### ISSUE TITLE
[feature] Remember scroll state while navigating

### ISSUE THREAD

**Issue by onny** [vixalien/muzika#49]
Hey,
considering scrolling through an artist page and checking albums

![image](https://github.com/vixalien/muzika/assets/757752/69974975-af0d-42b7-b6c8-ba28f22f49d0)

clicking on an album

![image](https://github.com/vixalien/muzika/assets/757752/b17e2f0b-461d-46d2-9c26-1c82f44434f3)

when navigating back to the artist page, we're on top again

![image](https://github.com/vixalien/muzika/assets/757752/844f723b-885c-4922-9359-4c60f5785619)

in the best case, the scroll position should be the same as on picture one. Checked the behaviour on other clients like Spotify on iOS and there it also remembers the scroll position.

This feature would be nice to have on mobile phones.

Best regards and thanks for the great app
Jonas

**Comment by vixalien** [comment]
alright! will work on this.
