### ISSUE TITLE
Flatpak bundles

### ISSUE THREAD

**Issue by orowith2os** [vixalien/muzika#5]
Muzika is currently still in its development phase, but is looking very promising. I know some people would like to try it out, and submitting it to Flathub may not be the best idea right now, as it's not something that should be easily available to end users; however, it should be possible to put together some per-commit Flatpak bundles and an OCI remote in GitHub Actions so it can be more accessible to those that want to try it out. [Inochi2D](https://github.com/Inochi2D) was going to make a nightly repo at first, so it may be able to take from that, but we ended up just going with standalone bundles for nightlies.

**Comment by orowith2os** [comment]
Hm, where is this bundle? I'm not seeing it in the CI. It's mentioned, but no option to download it.

**Comment by vixalien** [comment]
1. Go to Actions and then select the latest run (the topmost one)

2. Click on "Summary" in the navigation sidebar (on the right)

3. Under "Artifacts" you'll see a flatpak

![image](https://github.com/vixalien/muzika/assets/37999241/ff482f59-b7d6-4d03-a606-66070f6ba86d)


> Note: Make sure to select "Summary" on the right

**Comment by vixalien** [comment]
did you find the flatpak?

**Comment by orowith2os** [comment]
Oh, yes, I did. Sorry. GitHub's UI was just confusing.
