### ISSUE TITLE
unable to play music

### ISSUE THREAD

**Issue by Radical4ever** [vixalien/muzika#56]
hi, so when i start the app and try to play a song it hangs and it doesnt play it, running it on a terminal drops me the next error:

`(com.vixalien.muzika:2): Gjs-Console-CRITICAL **: 12:12:56.014: error during playback GstPlay.PlayError: Error from element /GstPlayBin3:playbin3/GstURIDecodeBin3:uridecodebin3-0/GstURISourceBin:urisourcebin0/GstDashDemux:dashdemux0: Resource not found.
Not Found: ../ext/soup/gstsouphttpsrc.c(1683): gst_soup_http_src_parse_status (): /GstPlayBin3:playbin3/GstURIDecodeBin3:uridecodebin3-0/GstURISourceBin:urisourcebin0/GstDashDemux:dashdemux0/GstBin:srcbin-audio_00/GstSoupHTTPSrc:souphttpsrc0:
Not Found (404), URL: https://rr1---sn-j5c5nx-nnul.googlevideo.com/videoplayback, Redirect to: (NULL)`
`Error on stream '':audio_00`
`(com.vixalien.muzika:2): Gtk-CRITICAL **: 12:12:56.015: gtk_media_stream_update: assertion 'gtk_media_stream_is_prepared (self)' failed
`

tried it on gnome-builder

**Comment by vixalien** [comment]
hmm interesting. looks like the URL is not properly escaped. can you pull the latest changes and let me know if the error persists?

**Comment by tsbarnes** [comment]
I'm still unable to play music with the latest update, there are no errors in the terminal but the music just buffers forever and never plays.

**Comment by Radical4ever** [comment]
> hmm interesting. looks like the URL is not properly escaped. can you pull the latest changes and let me know if the error persists?

The error still persist, now i dont get the message from before, but when i clear the app data and restart the app i get this error instead
`(com.vixalien.muzika:2): Gjs-Console-CRITICAL **: 10:25:53.305: Failed to load store, resetting {
    "stack": "GioFileStore@resource:///com/vixalien/muzika/js/main.js:25721:49\n@resource:///com/vixalien/muzika/js/main.js:25757:14\n@file:///app/bin/com.vixalien.muzika:28:6\n",
    "fileName": "resource:///com/vixalien/muzika/js/main.js",
    "lineNumber": 25721,
    "columnNumber": 49
}`

**Comment by Radical4ever** [comment]
another weird thing is that when i first build the project it fails with something related to gst flatpak, but when i try it for a second time it builds normally and finish with no errors

**Comment by vixalien** [comment]
> I'm still unable to play music with the latest update, there are no errors in the terminal but the music just buffers forever and never plays.

I found out it's an issue with the old GStreamer. can you try playing the ![Nightly Flatpak buillds](https://github.com/vixalien/muzika/actions/workflows/build-nighly.yml) instead of the normal ones? The Nightly flatpak builds are different in the sense that they use the (yet-unreleased) GNOME master runtime instead of the GNOME 44 runtime.

**Comment by vixalien** [comment]
> The error still persist, now i dont get the message from before, but when i clear the app data and restart the app i get this error instead

this seems to be an error that the data store is somehow corrupted. as the error says, it should reset itself and work correctly on the next run.

> another weird thing is that when i first build the project it fails with something related to gst flatpak, but when i try it for a second time it builds normally and finish with no errors

it would be helpful if you showed the logs

these errors seem related to the 44 runtime. I'll try seeing if it's indeed the cause and will keep you updated.

**Comment by Radical4ever** [comment]
> > The error still persist, now i dont get the message from before, but when i clear the app data and restart the app i get this error instead
> 
> this seems to be an error that the data store is somehow corrupted. as the error says, it should reset itself and work correctly on the next run.
> 
> > another weird thing is that when i first build the project it fails with something related to gst flatpak, but when i try it for a second time it builds normally and finish with no errors
> 
> it would be helpful if you showed the logs
> 
> these errors seem related to the 44 runtime. I'll try seeing if it's indeed the cause and will keep you updated.

i could send you a log, but i dont know how to make logs

**Comment by Radical4ever** [comment]
> > I'm still unable to play music with the latest update, there are no errors in the terminal but the music just buffers forever and never plays.
> 
> I found out it's an issue with the old GStreamer. can you try playing the ![Nightly Flatpak buillds](https://github.com/vixalien/muzika/actions/workflows/build-nighly.yml) instead of the normal ones? The Nightly flatpak builds are different in the sense that they use the (yet-unreleased) GNOME master runtime instead of the GNOME 44 runtime.

running nightly builds drops me the next error `(com.vixalien.muzika:2): Gtk-WARNING **: 13:55:49.748: (../gtk/gtksectionmodel.c:144):gtk_section_model_get_section: runtime check failed: (*out_start < *out_end)`

`(com.vixalien.muzika:2): Gtk-CRITICAL **: 13:55:49.748: gtk_bitset_get_size_in_range: assertion 'last >= first' failed`

`(com.vixalien.muzika:2): Gtk-WARNING **: 13:55:49.748: (../gtk/gtksectionmodel.c:144):gtk_section_model_get_section: runtime check failed: (*out_start < *out_end)`

`(com.vixalien.muzika:2): Gtk-WARNING **: 13:55:49.748: (../gtk/gtksectionmodel.c:144):gtk_section_model_get_section: runtime check failed: (*out_start < *out_end)`
** 
`Gtk:ERROR:../gtk/gtklistitemmanager.c:1313:gtk_list_item_manager_ensure_items: assertion failed: (header != NULL && header->widget == NULL)
Bail out! Gtk:ERROR:../gtk/gtklistitemmanager.c:1313:gtk_list_item_manager_ensure_items: assertion failed: (header != NULL && header->widget == NULL)`

**Comment by Radical4ever** [comment]
and switching to the devel configuration in gnome builder drops me the next error while building `[2/5] Generating data/ui/blueprints with a custom command
FAILED: data/ui/ui 
/app/bin/blueprint-compiler batch-compile data/ui/ui ../data/ui ../data/ui/components/album/item.blp ../data/ui/components/carousel/card.blp ../data/ui/components/carousel/carousel.blp ../data/ui/components/carousel/flatsong.blp ../data/ui/components/carousel/moodbox.blp ../data/ui/components/dynamic-image.blp ../data/ui/components/library/history.blp ../data/ui/components/library/mixedcard.blp ../data/ui/components/library/songs.blp ../data/ui/components/library/view.blp ../data/ui/components/loading.blp ../data/ui/components/nav/page.blp ../data/ui/components/navbar/button.blp ../data/ui/components/navbar/index.blp ../data/ui/components/navbar/section.blp ../data/ui/components/navbar/title.blp ../data/ui/components/paginator.blp ../data/ui/components/player/video/controls.blp ../data/ui/components/player/video/full.blp ../data/ui/components/player/video/mini.blp ../data/ui/components/player/video/view.blp ../data/ui/components/player/video/volume-controls.blp ../data/ui/components/player/full.blp ../data/ui/components/player/lyrics.blp ../data/ui/components/player/mini.blp ../data/ui/components/player/preview.blp ../data/ui/components/player/queue.blp ../data/ui/components/player/queueitem.blp ../data/ui/components/player/related.blp ../data/ui/components/playlist-image.blp ../data/ui/components/playlist/bar.blp ../data/ui/components/playlist/edit.blp ../data/ui/components/playlist/item.blp ../data/ui/components/playlist/largeheader.blp ../data/ui/components/playlist/listitem.blp ../data/ui/components/playlist/miniheader.blp ../data/ui/components/search/inlinecard.blp ../data/ui/components/search/section.blp ../data/ui/components/search/songcard.blp ../data/ui/components/search/topresult.blp ../data/ui/components/search/topresultsection.blp ../data/ui/gtk/help-overlay.blp ../data/ui/pages/album.blp ../data/ui/pages/artist-albums.blp ../data/ui/pages/artist.blp ../data/ui/pages/authentication-error.blp ../data/ui/pages/channel.blp ../data/ui/pages/charts.blp ../data/ui/pages/channel-playlists.blp ../data/ui/pages/error.blp ../data/ui/pages/explore.blp ../data/ui/pages/home.blp ../data/ui/pages/login.blp ../data/ui/pages/mood-playlists.blp ../data/ui/pages/moods.blp ../data/ui/pages/new-releases.blp ../data/ui/pages/playlist.blp ../data/ui/pages/search.blp ../data/ui/window.blp
error: Namespace Adw does not contain a type called ToolbarView
at ../data/ui/components/library/history.blp line 5 column 7:
   5 |  Adw.ToolbarView {
     |      ^
hint: Did you check your spelling?
hint: Are your dependencies up to date?`

`[3/5] Generating src/typescript-compile with a custom command`
`yarn run v1.22.19`

**Comment by Radical4ever** [comment]
> > another weird thing is that when i first build the project it fails with something related to gst flatpak, but when i try it for a second time it builds normally and finish with no errors
> 
> it would be helpful if you showed the logs
> 
> these errors seem related to the 44 runtime. I'll try seeing if it's indeed the cause and will keep you updated.

i leave the error that drops me when i first build the app:
`stripping /home/julian/.var/app/org.gnome.Builder/cache/gnome-builder/projects/muzika/flatpak/staging/x86_64-main/files/bin/sassc to /home/julian/.var/app/org.gnome.Builder/cache/gnome-builder/projects/muzika/flatpak/staging/x86_64-main/files/lib/debug/bin/sassc.debug
Committing stage build-sassc to cache

** (flatpak-builder:890): WARNING **: 18:06:07.165: Failed to get current git checksum: Falló al cambiar a la carpeta «/home/julian/Proyectos/muzika/.flatpak-builder/git/https_gitlab.gnome.org_GNOME_gtk.git» (No existe el fichero o el directorio)

** (flatpak-builder:890): WARNING **: 18:06:07.165: rofiles-fuse not available, doing without
========================================================================
Building module gtk in /home/julian/Proyectos/muzika/.flatpak-builder/build/gtk-1
========================================================================
cp: cannot stat '/home/julian/Proyectos/muzika/.flatpak-builder/git/https_gitlab.gnome.org_GNOME_gtk.git': No such file or directory
Error: module gtk: El proceso hijo terminó con el código 1`

**Comment by vixalien** [comment]
> hint: Are your dependencies up to date?`

this means you don't have libadwaita 1.4. Do you have `org.gnome.Sdk//master` from `gnome-nightly` installed and up-to-date?

**Comment by vixalien** [comment]
also can you please edit your posts to format your code blocks with triple dashes (```) instead of single dashes (`) so that I can read the output clearly?

**Comment by vixalien** [comment]
@tsbarnes what happens when you switch to the devel package?

**Comment by Radical4ever** [comment]
> @tsbarnes what happens when you switch to the devel package?

Ok so it drops me  the issue mentioned here

> and switching to the devel configuration in gnome builder drops me the next error while building
> 
> ```
> [2/5] Generating data/ui/blueprints with a custom command
> FAILED: data/ui/ui 
> /app/bin/blueprint-compiler batch-compile data/ui/ui ../data/ui ../data/ui/components/album/item.blp ../data/ui/components/carousel/card.blp ../data/ui/components/carousel/carousel.blp ../data/ui/components/carousel/flatsong.blp ../data/ui/components/carousel/moodbox.blp ../data/ui/components/dynamic-image.blp ../data/ui/components/library/history.blp ../data/ui/components/library/mixedcard.blp ../data/ui/components/library/songs.blp ../data/ui/components/library/view.blp ../data/ui/components/loading.blp ../data/ui/components/nav/page.blp ../data/ui/components/navbar/button.blp ../data/ui/components/navbar/index.blp ../data/ui/components/navbar/section.blp ../data/ui/components/navbar/title.blp ../data/ui/components/paginator.blp ../data/ui/components/player/video/controls.blp ../data/ui/components/player/video/full.blp ../data/ui/components/player/video/mini.blp ../data/ui/components/player/video/view.blp ../data/ui/components/player/video/volume-controls.blp ../data/ui/components/player/full.blp ../data/ui/components/player/lyrics.blp ../data/ui/components/player/mini.blp ../data/ui/components/player/preview.blp ../data/ui/components/player/queue.blp ../data/ui/components/player/queueitem.blp ../data/ui/components/player/related.blp ../data/ui/components/playlist-image.blp ../data/ui/components/playlist/bar.blp ../data/ui/components/playlist/edit.blp ../data/ui/components/playlist/item.blp ../data/ui/components/playlist/largeheader.blp ../data/ui/components/playlist/listitem.blp ../data/ui/components/playlist/miniheader.blp ../data/ui/components/search/inlinecard.blp ../data/ui/components/search/section.blp ../data/ui/components/search/songcard.blp ../data/ui/components/search/topresult.blp ../data/ui/components/search/topresultsection.blp ../data/ui/gtk/help-overlay.blp ../data/ui/pages/album.blp ../data/ui/pages/artist-albums.blp ../data/ui/pages/artist.blp ../data/ui/pages/authentication-error.blp ../data/ui/pages/channel.blp ../data/ui/pages/charts.blp ../data/ui/pages/channel-playlists.blp ../data/ui/pages/error.blp ../data/ui/pages/explore.blp ../data/ui/pages/home.blp ../data/ui/pages/login.blp ../data/ui/pages/mood-playlists.blp ../data/ui/pages/moods.blp ../data/ui/pages/new-releases.blp ../data/ui/pages/playlist.blp ../data/ui/pages/search.blp ../data/ui/window.blp
> error: Namespace Adw does not contain a type called ToolbarView
> at ../data/ui/components/library/history.blp line 5 column 7:
>    5 |  Adw.ToolbarView {
>      |      ^
> hint: Did you check your spelling?
> hint: Are your dependencies up to date?`
> 
> `[3/5] Generating src/typescript-compile with a custom command`
> `yarn run v1.22.19`
> ```

but after updating gnome sdk master on gnome builder and installing it locally the app now builds without issues on the devel package, i've got at first row 1 issue related to gs-plugin but rebuilding it solved it and other with yarn deps that i press build button again, and after that it build the app normally and now i can play music!

**Comment by Radical4ever** [comment]
this was on y case i didnt noticed the user mention 🤣

**Comment by tsbarnes** [comment]
> @tsbarnes what happens when you switch to the devel package?

I haven't tried it yet, I'll try it tonight.

**Comment by Radical4ever** [comment]
ok so, exporting the app and installing it drops the next error and doesnt start:
```
Gjs-Console-Message: 21:47:55.686: caching soup requests at /home/julian/.var/app/com.vixalien.muzika/cache/com.vixalien.muzika/soup-cache
Gjs-Console-Message: 21:47:55.692: storing token to secret store
Gjs-Console-Message: 21:47:55.761: caching data /home/julian/.var/app/com.vixalien.muzika/cache/com.vixalien.muzika/cache
Gjs-Console-Message: 21:47:55.806: storing data at /home/julian/.var/app/com.vixalien.muzika/data/com.vixalien.muzika/store.json

(com.vixalien.muzika:2): Gtk-WARNING **: 21:47:56.031: (../gtk/gtksectionmodel.c:144):gtk_section_model_get_section: runtime check failed: (*out_start < *out_end)

(com.vixalien.muzika:2): Gtk-CRITICAL **: 21:47:56.031: gtk_bitset_get_size_in_range: assertion 'last >= first' failed

(com.vixalien.muzika:2): Gtk-WARNING **: 21:47:56.031: (../gtk/gtksectionmodel.c:144):gtk_section_model_get_section: runtime check failed: (*out_start < *out_end)

(com.vixalien.muzika:2): Gtk-WARNING **: 21:47:56.031: (../gtk/gtksectionmodel.c:144):gtk_section_model_get_section: runtime check failed: (*out_start < *out_end)
**
Gtk:ERROR:../gtk/gtklistitemmanager.c:1313:gtk_list_item_manager_ensure_items: assertion failed: (header != NULL && header->widget == NULL)
Bail out! Gtk:ERROR:../gtk/gtklistitemmanager.c:1313:gtk_list_item_manager_ensure_items: assertion failed: (header != NULL && header->widget == NULL)
```

**Comment by vixalien** [comment]
yea it still depends on `org.gnome.Sdk` version master. not sure if you have that installed

**Comment by Radical4ever** [comment]
> org.gnome.Sdk

i have installed it

**Comment by Radical4ever** [comment]
> yea it still depends on `org.gnome.Sdk` version master. not sure if you have that installed

ok so when i install the .flatpak file i didnt noticed that my `org.gnome.Sdk` was on the flathub-beta origin so i just removed it and installed the gnome-nightly one and the app now runs installed on my os!
