### ISSUE TITLE
Feature request: Copy URL

### ISSUE THREAD

**Issue by julianfairfax** [vixalien/muzika#57]
Add an option to allow copying the URL of a song, album, artist, etc. for sharing purposes.

**Comment by vixalien** [comment]
right on!

**Comment by vixalien** [comment]
pages that would benefit from a Copy URL button:

- [ ] Playlist
- [ ] Album
- [ ] Artist
- [ ] Channel
- [ ] Artist Albums???
- [ ] Channel playlists??
- [ ] Mood

**Comment by vixalien** [comment]
fixed by 9d94a34f025efbb56e5f16041d9879dc713c085c
