### ISSUE TITLE
"Did you mean?" suggestion has wrong formatting

### ISSUE THREAD

**Issue by onny** [vixalien/muzika#69]
![image](https://github.com/vixalien/muzika/assets/757752/846cfb33-3ac9-4ebf-a81f-45f1bd1c9e25)

**Comment by vixalien** [comment]
not sure what's happening. it works correctly for me. did you update the app? if yes can you share with me the search term that triggers it (if possible)

![image](https://github.com/vixalien/muzika/assets/37999241/0e598368-0858-4fbe-893b-011dfce74fef)

**Comment by onny** [comment]
This is what I searched for

![image](https://github.com/vixalien/muzika/assets/757752/bbfe8b21-ffc4-4129-841b-d331b9a4fa37)

The error appears after searching / filter only songs

![image](https://github.com/vixalien/muzika/assets/757752/dcd3503e-19c9-4ece-9fd5-fda184334032)

**Comment by vixalien** [comment]
thanks for the context. will take a deeper look tomorrow

**Comment by vixalien** [comment]
fixed by bcf9d09
