### ISSUE TITLE
Show more singles / albums fail

### ISSUE THREAD

**Issue by onny** [vixalien/muzika#70]
Clicking on more singles or albums fails on mobile

![BE502AE9-2BDD-413E-B9D9-904B6E15B25E](https://github.com/vixalien/muzika/assets/757752/068b62d4-3a76-4d26-829c-80b68a50a672)
![81A06FB8-8791-42F9-885B-6870BD9558F0](https://github.com/vixalien/muzika/assets/757752/2a307037-5414-4e73-ab01-9f23e3b420d5)

**Comment by vixalien** [comment]
noticed this too. will be working on it

**Comment by vixalien** [comment]
should be fixed by 08f207d412aa22c4f784e42cafc3a81ad6b42ddf
