### ISSUE TITLE
login doesn't persist

### ISSUE THREAD

**Issue by mikelpr** [vixalien/muzika#79]
concisely: logged in, closed the app, reopened and it was back to before logging in the first time I opened the app

**Comment by vixalien** [comment]
did you take a look at the logs? did they say anything

**Comment by mikelpr** [comment]
I tried to redo this today and it worked just fine  🙃 the only difference I can think of is I logged in in via chrome on this same computer this time and last time I used my phone

**Comment by vixalien** [comment]
I notice this sometimes, too. Sometimes the first time will fail, but the other times work fine. Still need to investigate this

**Comment by gregthwuen** [comment]
I remember experiencing this too, waiting for a minute before closing the app after logging in the first time seemed to fix this. Could try to reproduce if that helps.

**Comment by vixalien** [comment]
> I remember experiencing this too, waiting for a minute before closing the app after logging in the first time seemed to fix this. Could try to reproduce if that helps.

It seems it's something related to us using the secret service (via libsecret) to store the authentication key. You can try to reproduce and I'll make sure to fix it

**Comment by parkerlreed** [comment]
Purely running on Plasma Wayland it would never save my login (no apparent error messages on stdout)

Loaded into COSMIC after an update today, and after launching, signing in, closing, reopening it stuck.

Back in Plasma it remembered now too. Persisting across session and reboots.
