### ISSUE TITLE
Synk upgrade suggestions

### ISSUE THREAD

**Issue by sabriunal** [vixalien/muzika#82]
Could you check the following suggestions. They are created via Synk services automatically. 

![resim](https://github.com/vixalien/muzika/assets/6218679/4e436fa9-91e6-4d38-a474-c542942e0203)

https://github.com/sabriunal/muzika/pulls?q=is%3Apr+is%3Aclosed

**Comment by vixalien** [comment]
Oh I'm gonna enable GitHub dependabot here instead. It do seem like your repo is outdated though..
